name: Sync

on: [push, pull_request, workflow_dispatch]

env:
  AWS_ACCOUNT: 476531600727
  AWS_REGION: ap-northeast-1
  AWS_ROLE_NAME: gha-mwaa
  DESTINATION_BUCKET: mwaa-476531600727-20230704115049092400000003

jobs:
  sync:
    runs-on: [self-hosted, linux, x64]
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials with IAM Role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT }}:role/${{ env.AWS_ROLE_NAME }}
          aws-region: ${{ env.AWS_REGION }}
      - name: List Buckets (as Debug)
        run: aws s3 ls
      - name: Sync Plugins 
        run: aws s3 sync plugins s3://${{ env.DESTINATION_BUCKET }}/plugins
      - name: Copy startup.sh
        run: aws s3 cp startup_script/startup.sh s3://${{ env.DESTINATION_BUCKET }}/startup.sh
      - name: Copy requirements.txt
        run: aws s3 cp requirements.txt s3://${{ env.DESTINATION_BUCKET }}/requirements.txt
      - name: Sync DAG files
        run: aws s3 sync dags s3://${{ env.DESTINATION_BUCKET }}/dags --exclude "dags/__pycache__/*"
